### ISSUE TITLE
File location question: vgpm_func.R?

### ISSUE THREAD

**Issue by jefferycsauer** [OHI-Science/ohiprep#88]
Hi there!

Quick question - is there supposed to be a common location for the vgpm_func.R script referenced here (http://ohi-science.org/ohiprep_v2018/globalprep/prs_fish/v2018/npp.html#calculate_mean_annual_npp)? 

Thanks!

Best,

J

**Comment by jafflerbach** [comment]
Here you go: https://github.com/OHI-Science/ohiprep_v2018/blob/0d8baaff7fdce439a1e4bce99d8f2030be83d504/globalprep/prs_fish/v2018/R/vgpm_func.R

**Comment by jefferycsauer** [comment]
Thanks for the rapid response!
